name: 'Close old reliability reports'
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
    issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'Closing old reliability report in **1** day'
          close-issue-message: 'Closed old reliability report'
          only-labels: 'reliability-report'
          days-before-stale: 6
          days-before-close: 1
